# Generated by Django 6.1 on 2026-08-17 12:23

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('tasks', 'Category')

    Category.objects.get_or_create(
        name='backend',
        slug='backend',
    )
    Category.objects.get_or_create(
        name='frontend',
        slug='frontend',
    )
    Category.objects.get_or_create(
        name='general',
        slug='general',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]